// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_Sach.Models;

namespace QL_Sach.Migrations
{
    [DbContext(typeof(QL_SachContext))]
    partial class QL_SachContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("QL_Sach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("IdBook");

                    b.Property<string>("NameBook");

                    b.Property<int?>("NumPage");

                    b.Property<double?>("Price");

                    b.Property<string>("PublishingCompany");

                    b.Property<string>("TypeBook");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
